const regionMap = {
  "01": "Stranci u BiH",
  "02": "Stranci u Crnog Gori",
  "03": "Stranci u Hrvatskoj",
  "04": "Stranci u Makedoniji",
  "05": "Stranci u Sloveniji",
  "07": "Stranci u Srbiji bez pokrajina",
  "08": "Stranci u Vojvodini",
  "09": "Stranci na Kosovu i metohiji",

  "10": "Banjaluka",
  "11": "Bihac",
  "12": "Doboj",
  "13": "Gorazde",
  "14": "Livno",
  "15": "Mostar",
  "16": "Prijedor",
  "17": "Sarajevo",
  "18": "Tuzla",
  "19": "Zenica",

  "21": "Podgorica",
  "26": "Niksic",
  "29": "Pljevlja",

  "30": "Osijek, Slavonija region",
  "31": "Bjelovar, Virovitica, Koprivnica, Pakrac, Podravina region",
  "32": "Varaždin, Međimurje region",
  "33": "Zagreb",
  "34": "Karlovac",
  "35": "Gospić, Lika region",
  "36": "Rijeka, Pula, Istra and Primorje region",
  "37": "Sisak, Banovina region",
  "38": "Split, Zadar, Dubrovnik, Dalmacija region",
  "39": "ostalo",

  "41": "Bitola",
  "42": "Kumanovo",
  "43": "Ohrid",
  "44": "Prilep",
  "45": "Skopje",
  "46": "Strumica",
  "47": "Tetovo",
  "48": "Veles",
  "49": "Štip",

  "50": "Slovenija",

  "71": "Beograd region",
  "72": "Šumadija",
  "73": "Niš region",
  "74": "Južna Morava",
  "75": "Zaječar",
  "76": "Podunavlje",
  "77": "Podrinje i Kolubara",
  "78": "Kraljevo region",
  "79": "Užice region",

  "80": "Novi Sad region",
  "81": "Sombor region",
  "82": "Subotica region",
  "85": "Zrenjanin region",
  "86": "Pančevo region",
  "87": "Kikinda region",
  "88": "Ruma region",
  "89": "Sremska Mitrovica region",

  "91": "Priština region",
  "92": "Kosovska Mitrovica region",
  "93": "Peć region",
  "94": "Đakovica region",
  "95": "Prizren region",
  "96": "Kosovsko Pomoravski okrug",
};

export default regionMap;
